version: '3'
services:
  backend:
    build:
      context: ./django
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./react
    volumes:
      - react_build: /react/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8000
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend
volume:
  react_build


