# Generated by Django 5.0.2 on 2024-03-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_humanmodel_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="humanmodel",
            name="model_file",
        ),
        migrations.AddField(
            model_name="humanmodel",
            name="model_path",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
